services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: dev
      MARIADB_USER: user
      MARIADB_PASSWORD: user
    restart: always
    volumes:
      - ./docker/conf:/etc/mysql/conf.d:ro
      - ./docker/init:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"

volumes:
  mariadb_data:
